name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Install deploy dependencies
        run: |
          cd deploy
          yarn install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897469443626:role/RuffenGitHubActionsRole-GitHubActionsRole
          role-session-name: GitHubActions-CDK-Deploy
          aws-region: eu-west-1

      - name: Deploy to AWS
        run: |
          cd deploy
          yarn cdk deploy RuffenStaticSite --require-approval never
        env:
          AWS_DEFAULT_REGION: eu-west-1
      
      - uses: sarisia/actions-status-discord@v1
        name: Notify
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: "Deploy Ruffen site"
          username: GitHub Actions
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
